version: '2'
services:
  vpn:
    build: ./vpn
    cap_add:
      - NET_ADMIN
    # This can be commented out, it just won't be able to load the sysctl.conf with optimum settings
    # You could make those changes on the host system instead
    privileged: true  
    devices:
      - '/dev/net/tun' 
    dns: # From https://www.ipredator.se/page/services#service_dns
      - 194.132.32.32
      - 46.246.46.246
    # These get defined by running ./up.py
    environment: 
      - IPRED_USER=${IPRED_USER}
      - IPRED_PASSWORD=${IPRED_PASSWORD}
    restart: always
  transmission:
    build: ./transmission
    depends_on:
      - vpn
    # This makes transmission use networking from vpn container
    network_mode: "service:vpn"  
    volumes:
      - ${DOWNLOADS_IN_PROGRESS}:/mnt/Downloads_In_Progress
      - ${DOWNLOADS_COMPLETED}:/mnt/Downloads_Completed
      # Using a named volume to allow the config directory to persist reboot
      - transmission_config:/home/transmission/.config
    restart: always
    environment: 
      - TRANSMISSION_UID=${TRANSMISSION_UID}
      - TRANSMISSION_GID=${TRANSMISSION_GID}
      - TRANSMISSION_DAEMON_ARGS=${TRANSMISSION_DAEMON_ARGS}
  portforward:
    build: ./portforward
    restart: always
    ports:
      - "9091:9091"
    depends_on:
      - transmission 
    links:
      - vpn:transmission 
volumes:
  transmission_config:
